#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@shadowsocks-rust-server[-1]
	add ucitrack shadowsocks-rust-server
	set ucitrack.@shadowsocks-rust-server[-1].init=shadowsocks-rust-server
	commit ucitrack
EOF

# Ensure config file exists
[ -f /etc/config/shadowsocks-rust-server ] || touch /etc/config/shadowsocks-rust-server

chmod +x /etc/init.d/shadowsocks-rust-server 2>/dev/null

exit 0
