'use strict';
'require view';
'require form';
'require uci';
'require rpc';
'require fs';

var callServiceList = rpc.declare({
	object: 'service',
	method: 'list',
	params: ['name'],
	expect: { '': {} }
});

var encryption_methods = [
	// AEAD 2022 (recommended)
	'2022-blake3-aes-128-gcm',
	'2022-blake3-aes-256-gcm',
	'2022-blake3-chacha20-poly1305',
	'2022-blake3-chacha8-poly1305',
	// Standard AEAD
	'aes-128-gcm',
	'aes-256-gcm',
	'chacha20-ietf-poly1305',
	'xchacha20-ietf-poly1305',
	// Other AEAD
	'aes-128-ccm',
	'aes-256-ccm',
	'aes-128-gcm-siv',
	'aes-256-gcm-siv',
	// Legacy stream ciphers
	'chacha20-ietf',
	'aes-128-cfb',
	'aes-256-cfb',
	'aes-128-ctr',
	'aes-256-ctr',
	'rc4-md5',
	'none',
];

function getServiceStatus() {
	return L.resolveDefault(callServiceList('server-rust-luc'), {})
		.then(function(res) {
			var isRunning = false;
			try {
				isRunning = res['server-rust-luc']['instances'] != null;
			} catch(e) {}
			return isRunning;
		});
}

function renderStatus(isRunning) {
	var spanTemp = '<span style="color:%s;font-weight:bold">%s</span>';
	if (isRunning) {
		return String.format(spanTemp, 'green', _('Running'));
	} else {
		return String.format(spanTemp, 'red', _('Not running'));
	}
}

return view.extend({
	load: function() {
		return Promise.all([
			getServiceStatus(),
			uci.load('server-rust-luc')
		]);
	},

	render: function(data) {
		var isRunning = data[0];
		var m, s, o;

		m = new form.Map('server-rust-luc', _('Server Rust Luc'),
			_('Configure server instances. Each instance runs as an independent process.'));

		/* Global settings */
		s = m.section(form.TypedSection, 'general', _('General Settings'));
		s.anonymous = true;
		s.addremove = false;

		o = s.option(form.DummyValue, '_status', _('Service Status'));
		o.rawhtml = true;
		o.cfgvalue = function() {
			return renderStatus(isRunning);
		};

		o = s.option(form.Flag, 'enabled', _('Enable'));
		o.default = '0';
		o.rmempty = false;

		o = s.option(form.ListValue, 'log_level', _('Log Level'));
		o.value('error', _('Error'));
		o.value('warn', _('Warning'));
		o.value('info', _('Info'));
		o.value('debug', _('Debug'));
		o.value('trace', _('Trace'));
		o.default = 'info';

		/* Server instances */
		s = m.section(form.TypedSection, 'server', _('Server Instances'));
		s.addremove = true;
		s.anonymous = false;
		s.template = 'cbi/tblsection';

		o = s.option(form.Flag, 'enabled', _('Enable'));
		o.default = '1';
		o.rmempty = false;

		o = s.option(form.Value, 'server', _('Listen Address'));
		o.placeholder = '0.0.0.0';
		o.default = '0.0.0.0';
		o.datatype = 'ipaddr';
		o.rmempty = false;

		o = s.option(form.Value, 'server_port', _('Listen Port'));
		o.placeholder = '8388';
		o.default = '8388';
		o.datatype = 'port';
		o.rmempty = false;

		o = s.option(form.ListValue, 'method', _('Encryption Method'));
		encryption_methods.forEach(function(m) {
			o.value(m, m);
		});
		o.default = 'aes-256-gcm';
		o.rmempty = false;

		o = s.option(form.Value, 'password', _('Password / Key'));
		o.password = true;
		o.rmempty = false;
		o.description = _('For 2022-blake3-* methods, use Base64 key generated by: ssservice genkey -m "METHOD"');

		o = s.option(form.Value, 'timeout', _('Timeout (s)'));
		o.placeholder = '300';
		o.default = '300';
		o.datatype = 'uinteger';

		o = s.option(form.ListValue, 'mode', _('TCP/UDP Mode'));
		o.value('tcp_only', _('TCP Only'));
		o.value('udp_only', _('UDP Only'));
		o.value('tcp_and_udp', _('TCP & UDP'));
		o.default = 'tcp_and_udp';

		o = s.option(form.Flag, 'no_delay', _('TCP No Delay'));
		o.default = '0';

		o = s.option(form.Flag, 'ipv6_first', _('IPv6 First'));
		o.default = '0';

		o = s.option(form.Value, 'plugin', _('Plugin'));
		o.placeholder = _('e.g. v2ray-plugin');
		o.optional = true;

		o = s.option(form.Value, 'plugin_opts', _('Plugin Options'));
		o.placeholder = _('e.g. server;tls;host=example.com');
		o.optional = true;
		o.depends('plugin', /./);

		o = s.option(form.Value, 'acl', _('ACL File'));
		o.placeholder = '/etc/server-rust-luc/acl/server.acl';
		o.optional = true;

		return m.render();
	}
});
